spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.144.158/blog?characterEncoding=utf-8
    username: root
    password: rzx991105++

    hikari:
      # 最小空闲链接
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 180000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.myblog.blog: debug
  file:
    name: myblog/aspect.log

#自定义评论区头像
comment.avatar: /img/avatar/avatar01.png